---
- name: save dumps
  hosts: main_server 
  become: yes
  tasks:
    - name: create new dump
      shell: cd /home/ubuntu/workspace %% docker compose exec -it db pg_dump -U test -d testdb > /home/ubuntu/workspace/dumps/dump-$(date '+%F|%H:%M:%S').dump
    - name: message on mail
      shell: echo "Dump обновился" | ssmtp -C/etc/ssmtp/ssmtp.conf god.winer@yandex.ru
