---

  - name: update repo
    shell: apt update
  
  - name: test
    shell: echo "{{TEST_VARS}}" >> /home/ubuntu/copy123.txt
  - name: test2
    shell: echo "proverka semaphore" >> /home/ubuntu/copy123.txt

